### ISSUE TITLE
（調査）TabLayout方法を調査する

### ISSUE THREAD

**Issue by takahashiyasuh** [takahashiyasuh/android#34]
API28のTabLayout方法を調査する。
現在だと、こんな感じになる

**Comment by takahashiyasuh** [comment]
エラーメッセージはこんな感じです。
 android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class android.support.design.widget.TabLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class android.support.design.widget.TabLayout
     Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class android.support.design.widget.TabLayout
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.TabLayout

**Comment by takahashiyasuh** [comment]
xmlに android.support.design.widget.TabLayout を追加すると以下のエラーを表示する。 

```
This view is not constrained vertically: at runtime it will jump to the top unless you add a vertical constraint more... (Ctrl+F1
```

**Comment by takahashiyasuh** [comment]
単純に、クラスが見付からないということなので、パスに必要なライブラリを追加します。
* [エラー：java.lang.NoClassDefFoundError Android](https://codeday.me/jp/qa/20190130/204488.html)

⇒「サポートライブラリとデザインライブラリのバージョンは同じでなければなりません。」ということでした。
設定画面で依存関係を調べて追加する方法もあるが、デザイン画面でTabLayoutの↓をダブルクリックして使用可能にしたことで解消できました。
**依存が面倒なコンポーネントはデザイン画面で追加した方が楽そうです！**
![tablayout2](https://user-images.githubusercontent.com/7280554/58368293-ec827180-7f25-11e9-8228-c151628c6ed7.PNG)
